services:
    postgres:
        image: postgres:17-alpine
        restart: unless-stopped
        ports:
            - ${POSTGRES_PORT}:5432
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - postgres-data:/var/lib/postgresql/data
    mongo:
        image: mongo:7-jammy
        restart: unless-stopped
        ports:
            - ${MONGO_PORT}:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongo-data:/data/db
    rabbit:
        image: rabbitmq:4.2.5-alpine
        restart: unless-stopped
        ports:
            - ${RABBIT_AMQP_PORT}:5672
            - ${RABBIT_UI_PORT}:15672
        environment:
            RABBIT_DEFAULT_USER: ${RABBIT_DEFAULT_USER}
            RABBIT_DEFAULT_PASS: ${RABBIT_DEFAULT_PASS}
        volumes:
            - rabbitmq-data:/var/lib/rabbitmq/
volumes:
    postgres-data:
    mongo-data:
    rabbitmq-data:
