spring.application.name=ms-auth
spring.mongodb.host=mongo
spring.mongodb.port=${MONGO_PORT}
spring.mongodb.database=bantads
spring.mongodb.username=${MONGO_INITDB_ROOT_USERNAME}
spring.mongodb.password=${MONGO_INITDB_ROOT_PASSWORD}
spring.mongodb.authentication-database=admin
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
server.port=8080