spring.application.name=ms-funcionario
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/bantads?currentSchema=schema_funcionario
spring.datasource.username=${DB_USER:bantads}
spring.datasource.password=${DB_PASS:bantads123}
jpa.hibernate.ddl-auto=update
jpa.show-sql=true
jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jpa.properties.hibernate.default_schema=schema_funcionario